"use client";

import { useState, useEffect } from "react";
import { QUESTION_TYPE_REGISTRY, listByCategory } from "@/app/admin/_lib/questionTypeRegistry";
import { getSchema } from "@/app/admin/_lib/questionSchemas";
import {
  AiConfig,
  DEFAULT_AI_CONFIG,
  isAiConfigured,
} from "@/app/admin/_lib/aiConfig";
import { QuestionSkill } from "@/app/admin/_lib/types";
import {
  ParsedAuthorQuestion,
  generateQuestionsFromPassage,
  persistGeneratedQuestions,
} from "@/app/admin/_lib/questionGeneration";

interface AiAuthorModalProps {
  sectionId: string;
  sectionTitle?: string;
  sectionPassage?: string | null;
  initialType?: string;
  initialSkill?: string;
  autoGenerate?: boolean;
  onGenerated?: (count: number) => void;
  onCancel: () => void;
}

export function AiAuthorModal({
  sectionId,
  sectionTitle,
  sectionPassage,
  initialType,
  initialSkill,
  autoGenerate = false,
  onGenerated,
  onCancel,
}: AiAuthorModalProps) {
  const initialPassage = (sectionPassage || "").trim();
  const [type, setType] = useState<string>(initialType || "CLASSIFICATION");
  const [skill, setSkill] = useState<string>(initialSkill || "READING");
  const [count, setCount] = useState<number>(1);
  const [passage, setPassage] = useState(initialPassage);
  const [useCustomPassage, setUseCustomPassage] = useState(!initialPassage);
  const [isPassageExpanded, setIsPassageExpanded] = useState(false);
  const [extraContext, setExtraContext] = useState("");
  const [config] = useState<AiConfig>(DEFAULT_AI_CONFIG);
  const [generating, setGenerating] = useState(false);
  const [resultText, setResultText] = useState<string | null>(null);
  const [parsedQuestions, setParsedQuestions] = useState<ParsedAuthorQuestion[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [validationErrors, setValidationErrors] = useState<string[]>([]);
  const [saving, setSaving] = useState(false);
  const [savedCount, setSavedCount] = useState(0);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const configured = isAiConfigured(config);
  const schema = getSchema(type);

  const runGeneration = async (
    genType: string,
    genSkill: string,
    genPassage: string,
    genCount: number,
    genExtra: string
  ) => {
    if (!configured) {
      setError(
        config.provider === "server-proxy"
          ? "AI endpoint not configured. Set NEXT_PUBLIC_AI_SERVICE_URL or NEXT_PUBLIC_GATEWAY_URL."
          : "AI not configured. Set NEXT_PUBLIC_AI_API_KEY in .env.local"
      );
      return;
    }
    if (!genPassage.trim()) {
      setError("Source passage is required.");
      return;
    }

    setError(null);
    setValidationErrors([]);
    setResultText(null);
    setParsedQuestions(null);
    setSavedCount(0);
    setGenerating(true);
    try {
      const result = await generateQuestionsFromPassage({
        config,
        type: genType,
        skill: genSkill,
        passage: genPassage.trim(),
        count: genCount,
        extraContext: genExtra.trim(),
        sectionId,
      });

      setResultText(result.rawText);
      setParsedQuestions(result.questions);
      setValidationErrors(result.validationErrors);

      if (result.validationErrors.length > 0) {
        setError(`Generated question(s) failed validation:\n${result.validationErrors.join("\n")}`);
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "AI call failed");
    } finally {
      setGenerating(false);
    }
  };

  useEffect(() => {
    if (autoGenerate && initialPassage && !hasAutoGenerated) {
      setHasAutoGenerated(true);
      runGeneration(type, skill, initialPassage, count, extraContext);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGenerate, initialPassage, hasAutoGenerated]);

  const handleGenerate = async () => {
    const activePassage = useCustomPassage ? passage : initialPassage || passage;
    await runGeneration(type, skill, activePassage, count, extraContext);
  };

  const handleSaveAll = async () => {
    if (!parsedQuestions || parsedQuestions.length === 0) return;
    setSaving(true);
    try {
      const saved = await persistGeneratedQuestions(sectionId, parsedQuestions);
      setSavedCount(saved);
      onGenerated?.(saved);
      onCancel();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Save failed");
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
      <div className="w-full max-w-3xl rounded-2xl bg-slate-900 border border-slate-800 shadow-2xl max-h-[90vh] flex flex-col">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 shrink-0">
          <div>
            <h2 className="text-base font-bold text-white flex items-center gap-2">
              <span>✨</span> AI Author Question
            </h2>
            <p className="text-xs text-slate-400 mt-0.5">
              Generate grounded question content using a large language model.
            </p>
          </div>
          <button onClick={onCancel} className="text-slate-500 hover:text-slate-300 text-xl">
            ✕
          </button>
        </div>

        {!configured && (
          <div className="mx-6 mt-4 p-3 rounded-md bg-amber-950/30 border border-amber-900/40 text-xs text-amber-200">
            ⚠ AI is not configured.{" "}
            {config.provider === "server-proxy" ? (
              <>
                Set <code className="px-1 bg-slate-800 rounded">NEXT_PUBLIC_GATEWAY_URL</code> or{" "}
                <code className="px-1 bg-slate-800 rounded">NEXT_PUBLIC_AI_SERVICE_URL</code> to enable generation.
              </>
            ) : (
              <>
                Set <code className="px-1 bg-slate-800 rounded">NEXT_PUBLIC_AI_API_KEY</code> in{" "}
                <code className="px-1 bg-slate-800 rounded">.env.local</code> to enable generation.
              </>
            )}
            {" "}The schema reference below is still available for manual authoring.
          </div>
        )}

        <div className="px-6 py-4 flex-1 overflow-y-auto space-y-4">
          <div className="grid grid-cols-3 gap-3">
            <div>
              <label className="block text-[11px] font-semibold text-slate-400 mb-1">
                Question Type
              </label>
              <select
                value={type}
                onChange={(e) => setType(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-md px-2.5 py-1.5 text-xs text-slate-100 focus:outline-none focus:border-indigo-500"
              >
                {listByCategory("mcq")
                  .concat(listByCategory("completion"))
                  .concat(listByCategory("matching"))
                  .concat(listByCategory("ordering"))
                  .concat(listByCategory("speaking"))
                  .map((m) => (
                    <option key={m.type} value={m.type}>
                      {m.label}
                    </option>
                  ))}
              </select>
            </div>
            <div>
              <label className="block text-[11px] font-semibold text-slate-400 mb-1">
                Skill
              </label>
              <select
                value={skill}
                onChange={(e) => setSkill(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-md px-2.5 py-1.5 text-xs text-slate-100 focus:outline-none focus:border-indigo-500"
              >
                {Object.values(QuestionSkill).map((s) => (
                  <option key={s} value={s}>
                    {s}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-[11px] font-semibold text-slate-400 mb-1">
                Number of questions
              </label>
              <input
                type="number"
                min={1}
                max={5}
                value={count}
                onChange={(e) => setCount(Math.max(1, Math.min(5, Number(e.target.value))))}
                className="w-full bg-slate-950 border border-slate-800 rounded-md px-2.5 py-1.5 text-xs text-slate-100 focus:outline-none focus:border-indigo-500"
              />
            </div>
          </div>

          {/* Section Passage Auto-Binding Card */}
          {initialPassage && !useCustomPassage ? (
            <div className="p-3.5 rounded-xl bg-slate-950/80 border border-slate-800 space-y-2.5">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 min-w-0">
                  <span className="text-base shrink-0">📄</span>
                  <div className="truncate">
                    <span className="text-xs font-semibold text-slate-200">
                      Using Section Passage:{" "}
                      <span className="text-indigo-300">
                        &ldquo;{sectionTitle || "Current Section"}&rdquo;
                      </span>
                    </span>
                    <span className="text-[11px] text-slate-500 ml-2">
                      ({initialPassage.length} chars)
                    </span>
                  </div>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <button
                    type="button"
                    onClick={() => setIsPassageExpanded((prev) => !prev)}
                    className="text-xs text-indigo-400 hover:text-indigo-300 font-medium transition"
                  >
                    {isPassageExpanded ? "Collapse preview" : "Expand preview"}
                  </button>
                  <span className="text-slate-600">|</span>
                  <button
                    type="button"
                    onClick={() => setUseCustomPassage(true)}
                    className="text-xs text-slate-400 hover:text-slate-200 transition"
                  >
                    Edit / Use custom passage
                  </button>
                </div>
              </div>
              {isPassageExpanded && (
                <div className="p-3 rounded-lg bg-slate-900/80 border border-slate-800/80 text-xs text-slate-300 font-mono whitespace-pre-wrap max-h-48 overflow-y-auto leading-relaxed">
                  {initialPassage}
                </div>
              )}
            </div>
          ) : (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="block text-[11px] font-semibold text-slate-400">
                  Source passage / content *
                </label>
                {initialPassage && useCustomPassage && (
                  <button
                    type="button"
                    onClick={() => {
                      setPassage(initialPassage);
                      setUseCustomPassage(false);
                    }}
                    className="text-xs text-indigo-400 hover:text-indigo-300 font-medium transition"
                  >
                    Revert to section passage
                  </button>
                )}
              </div>
              {!initialPassage && (
                <div className="p-2.5 rounded-lg bg-amber-950/20 border border-amber-900/30 text-xs text-amber-300 flex items-center gap-2">
                  <span>ℹ</span>
                  <span>Section has no passage yet. Paste your reading passage or transcript below:</span>
                </div>
              )}
              <textarea
                value={passage}
                onChange={(e) => setPassage(e.target.value)}
                rows={5}
                placeholder="Paste the reading passage, listening transcript, or speaking topic…"
                className="w-full bg-slate-950 border border-slate-800 rounded-md p-3 text-xs text-slate-100 font-mono placeholder-slate-600 focus:outline-none focus:border-indigo-500"
              />
            </div>
          )}

          <div>
            <label className="block text-[11px] font-semibold text-slate-400 mb-1">
              Extra instructions (optional)
            </label>
            <textarea
              value={extraContext}
              onChange={(e) => setExtraContext(e.target.value)}
              rows={2}
              placeholder="e.g. 'focus on paragraph 2' or 'use 3 categories only'"
              className="w-full bg-slate-950 border border-slate-800 rounded-md p-2 text-xs text-slate-100 placeholder-slate-600 focus:outline-none focus:border-indigo-500"
            />
          </div>

          <details className="text-[11px] text-slate-400">
            <summary className="cursor-pointer hover:text-slate-200">
              View {schema.label} schema
            </summary>
            <pre className="mt-2 p-3 rounded-md bg-slate-950 border border-slate-800 text-slate-300 overflow-x-auto font-mono">
              {schema.jsonShape}
            </pre>
            {schema.constraints.length > 0 && (
              <ul className="mt-2 ml-3 space-y-0.5 text-amber-300/80">
                {schema.constraints.map((c, i) => (
                  <li key={i}>· {c}</li>
                ))}
              </ul>
            )}
          </details>

          {error && (
            <div className="p-3 rounded-md bg-rose-950/30 border border-rose-900/40 text-xs text-rose-300 whitespace-pre-wrap">
              {error}
            </div>
          )}

          {resultText && (
            <details className="text-[11px]">
              <summary className="cursor-pointer text-slate-300">
                Raw LLM response
              </summary>
              <pre className="mt-2 p-2 rounded bg-slate-950 border border-slate-800 text-slate-300 overflow-x-auto max-h-48 overflow-y-auto font-mono">
                {resultText}
              </pre>
            </details>
          )}

          {parsedQuestions && parsedQuestions.length > 0 && (
            <div className="p-3 rounded-md bg-emerald-950/20 border border-emerald-900/40">
              <div className="text-xs font-bold text-emerald-200 mb-2">
                ✓ Parsed {parsedQuestions.length} question(s) — review then save
              </div>
              <div className="space-y-1.5 max-h-40 overflow-y-auto">
                {parsedQuestions.map((item, i) => (
                  <div key={i} className="text-[11px] text-emerald-200/80 flex items-center gap-2">
                    <span className="font-mono">#{i + 1}</span>
                    <span className="font-bold">{item.upsert.Type}</span>
                    <span className="truncate flex-1">{(item.upsert.PromptMd || "").slice(0, 80)}…</span>
                    {item.options && (
                      <span className="text-slate-400 text-[10px]">({item.options.length} options)</span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {savedCount > 0 && (
            <div className="p-3 rounded-md bg-emerald-950/30 border border-emerald-900/50 text-xs text-emerald-200">
              ✓ Saved {savedCount} question(s) to the section.
            </div>
          )}
        </div>

        <div className="px-6 py-4 border-t border-slate-800 flex items-center justify-end gap-2 shrink-0">
          <button
            type="button"
            onClick={onCancel}
            className="px-4 py-2 text-xs font-medium text-slate-400 hover:text-slate-200 rounded-lg transition"
          >
            Cancel
          </button>
          {parsedQuestions ? (
            <button
              type="button"
              onClick={handleSaveAll}
              disabled={saving || validationErrors.length > 0}
              className="px-4 py-2 text-xs font-semibold rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white shadow-lg shadow-emerald-600/30 transition active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {saving
                ? "Saving…"
                : validationErrors.length > 0
                ? "Cannot save invalid questions"
                : `Save ${parsedQuestions.length} to section`}
            </button>
          ) : (
            <button
              type="button"
              onClick={handleGenerate}
              disabled={!configured || generating}
              className="px-4 py-2 text-xs font-semibold rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg shadow-indigo-600/30 transition active:scale-95 disabled:opacity-50 flex items-center gap-2"
            >
              {generating ? (
                <>
                  <span className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  <span>Generating…</span>
                </>
              ) : (
                <span>Generate</span>
              )}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
